// mpx_env.ts — the raw host imports for AssemblyScript skills.
//
// GENERATED by tools/gen_abi.py. Do not edit.
// ABI version 4, 70 symbols.

export const MPX_ABI_VERSION: i32 = 4;

export const MPX_OK: i32 = 0;
export const MPX_ERR_ARG: i32 = -1;
export const MPX_ERR_NOT_LOCKED: i32 = -2;
export const MPX_ERR_NO_REPLY: i32 = -3;
export const MPX_ERR_READONLY: i32 = -4;
export const MPX_ERR_CANCELLED: i32 = -5;
export const MPX_ERR_STATE: i32 = -6;
export const MPX_ERR_BUSY: i32 = -7;

@external("env", "mpx_abi_version")
export declare function mpx_abi_version(): i32;

@external("env", "print")
export declare function print(a0: usize, a1: i32): i32;

@external("env", "robot_gait")
export declare function robot_gait(a0: usize): i32;

@external("env", "robot_get_mode")
export declare function robot_get_mode(): i32;

@external("env", "robot_set_body_pose")
export declare function robot_set_body_pose(a0: f32, a1: f32, a2: f32): i32;

@external("env", "robot_set_attitude_speed")
export declare function robot_set_attitude_speed(a0: i32): i32;

@external("env", "robot_set_attitude_speed_xyz")
export declare function robot_set_attitude_speed_xyz(a0: i32, a1: i32, a2: i32): i32;

@external("env", "robot_set_config")
export declare function robot_set_config(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32): i32;

@external("env", "robot_get_period")
export declare function robot_get_period(): i32;

@external("env", "robot_get_height")
export declare function robot_get_height(): i32;

@external("env", "robot_get_up_height")
export declare function robot_get_up_height(): i32;

@external("env", "robot_get_stride")
export declare function robot_get_stride(): i32;

@external("env", "robot_get_tilt")
export declare function robot_get_tilt(): i32;

@external("env", "robot_set_servo_angle")
export declare function robot_set_servo_angle(a0: i32, a1: i32): i32;

@external("env", "robot_flush")
export declare function robot_flush(): i32;

@external("env", "robot_set_servo_speed")
export declare function robot_set_servo_speed(a0: i32, a1: i32): i32;

@external("env", "robot_read_position")
export declare function robot_read_position(a0: i32): i32;

@external("env", "robot_read_angle_cdeg")
export declare function robot_read_angle_cdeg(a0: i32): i32;

@external("env", "robot_read_speed")
export declare function robot_read_speed(a0: i32): i32;

@external("env", "robot_read_load")
export declare function robot_read_load(a0: i32): i32;

@external("env", "robot_read_voltage")
export declare function robot_read_voltage(a0: i32): i32;

@external("env", "robot_read_temperature")
export declare function robot_read_temperature(a0: i32): i32;

@external("env", "robot_read_moving")
export declare function robot_read_moving(a0: i32): i32;

@external("env", "robot_read_current")
export declare function robot_read_current(a0: i32): i32;

@external("env", "robot_set_offset")
export declare function robot_set_offset(a0: i32, a1: i32): i32;

@external("env", "robot_get_offset")
export declare function robot_get_offset(a0: i32): i32;

@external("env", "robot_ping_servo")
export declare function robot_ping_servo(a0: i32): i32;

@external("env", "robot_delay_ms")
export declare function robot_delay_ms(a0: i32): i32;

@external("env", "robot_ik_fr")
export declare function robot_ik_fr(a0: f32, a1: f32, a2: f32): i32;

@external("env", "robot_ik_fl")
export declare function robot_ik_fl(a0: f32, a1: f32, a2: f32): i32;

@external("env", "robot_ik_rr")
export declare function robot_ik_rr(a0: f32, a1: f32, a2: f32): i32;

@external("env", "robot_ik_rl")
export declare function robot_ik_rl(a0: f32, a1: f32, a2: f32): i32;

@external("env", "robot_imu_read")
export declare function robot_imu_read(a0: i32): i32;

@external("env", "robot_imu_print")
export declare function robot_imu_print(): i32;

@external("env", "servo_lock")
export declare function servo_lock(): i32;

@external("env", "servo_unlock")
export declare function servo_unlock(): i32;

@external("env", "servo_is_locked")
export declare function servo_is_locked(): i32;

@external("env", "servo_set_gain")
export declare function servo_set_gain(a0: i32, a1: i32, a2: f32): i32;

@external("env", "servo_get_gain")
export declare function servo_get_gain(a0: i32, a1: i32, a2: i32): i32;

@external("env", "servo_save_config")
export declare function servo_save_config(a0: i32): i32;

@external("env", "servo_restore_config")
export declare function servo_restore_config(a0: i32): i32;

@external("env", "servo_stage")
export declare function servo_stage(a0: i32, a1: f32, a2: f32, a3: f32, a4: f32): i32;

@external("env", "servo_commit")
export declare function servo_commit(): i32;

@external("env", "servo_write_all")
export declare function servo_write_all(a0: i32, a1: i32): i32;

@external("env", "servo_read")
export declare function servo_read(a0: i32, a1: i32): i32;

@external("env", "servo_read_all")
export declare function servo_read_all(a0: i32): i32;

@external("env", "servo_poll")
export declare function servo_poll(): i32;

@external("env", "servo_direct")
export declare function servo_direct(a0: i32, a1: i32, a2: f32, a3: f32): i32;

@external("env", "servo_scan")
export declare function servo_scan(): i32;

@external("env", "mpx_control_take")
export declare function mpx_control_take(a0: i32): i32;

@external("env", "mpx_control_release")
export declare function mpx_control_release(): i32;

@external("env", "mpx_control_owner")
export declare function mpx_control_owner(): i32;

@external("env", "mpx_millis")
export declare function mpx_millis(): i32;

@external("env", "mpx_sleep_until")
export declare function mpx_sleep_until(a0: i32): i32;

@external("env", "mpx_drive")
export declare function mpx_drive(a0: f32, a1: f32, a2: f32): i32;

@external("env", "mpx_drive_stop")
export declare function mpx_drive_stop(): i32;

@external("env", "mpx_set_walk_speed")
export declare function mpx_set_walk_speed(a0: i32): i32;

@external("env", "mpx_get_walk_speed")
export declare function mpx_get_walk_speed(): i32;

@external("env", "mpx_foot")
export declare function mpx_foot(a0: i32, a1: f32, a2: f32, a3: f32): i32;

@external("env", "mpx_set_all_servo_speed")
export declare function mpx_set_all_servo_speed(a0: i32): i32;

@external("env", "mpx_reset_offsets")
export declare function mpx_reset_offsets(): i32;

@external("env", "mpx_read_temperature_c")
export declare function mpx_read_temperature_c(a0: i32): f32;

@external("env", "mpx_param_f")
export declare function mpx_param_f(a0: usize, a1: f32): f32;

@external("env", "mpx_param_i")
export declare function mpx_param_i(a0: usize, a1: i32): i32;

@external("env", "mpx_overlay")
export declare function mpx_overlay(a0: i32, a1: f32): i32;

@external("env", "mpx_overlay_get")
export declare function mpx_overlay_get(a0: i32): f32;

@external("env", "mpx_overlay_clear")
export declare function mpx_overlay_clear(): i32;

@external("env", "mpx_tick_every")
export declare function mpx_tick_every(a0: i32): i32;

@external("env", "mpx_tick_stop")
export declare function mpx_tick_stop(): i32;

@external("env", "mpx_trace")
export declare function mpx_trace(a0: usize, a1: f32): i32;
