/* mpx/gaits.h — the movements the robot already knows.
 *
 * A gait is a motion the firmware performs for you. You name one; it does the
 * rest. This is the highest control layer and the only one where a mistake in
 * your maths cannot put the robot on its side.
 *
 * The catalogue carries more than names. `kind` is the field people trip over:
 *
 *   MPX_GAIT_HOLDS     stays in its final pose until you change it. If your
 *                      skill exits here, the robot stays here.
 *   MPX_GAIT_RETURNS   performs once and comes back to standing by itself.
 *   MPX_GAIT_CYCLES    repeats until you stop it.
 *
 * `typical_ms` is how long one performance naturally takes — 0 means it runs
 * until stopped. {@link mpx_gait_play} uses it so you can write the movement
 * without timing it by hand.
 *
 * GENERATED by `python tools/gen_gaits.py --write` from the firmware's
 * robot::GaitCmd enum and robot.cc's GAIT_NAMES table, merged with
 * abi/gaits.json. Do not edit: the numbers are a wire protocol.
 */
#ifndef MPX_GAITS_H
#define MPX_GAITS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    MPX_GAIT_NONE             =  0,
    MPX_GAIT_STAND            =  1,   /* firmware name: init */
    MPX_GAIT_STEP             =  2,
    MPX_GAIT_ROLL             =  3,
    MPX_GAIT_PITCH            =  4,
    MPX_GAIT_STRETCH          =  5,
    MPX_GAIT_FORWARD          =  6,   /* firmware name: advance */
    MPX_GAIT_BACK             =  7,
    MPX_GAIT_STRAFE_LEFT      =  8,   /* firmware name: left */
    MPX_GAIT_STRAFE_RIGHT     =  9,   /* firmware name: right */
    MPX_GAIT_TURN_LEFT        = 10,   /* firmware name: turnL */
    MPX_GAIT_TURN_RIGHT       = 11,   /* firmware name: turnR */
    MPX_GAIT_TWERK            = 12,
    MPX_GAIT_JUMP             = 13,
    MPX_GAIT_JUMP_FORWARD     = 14,   /* firmware name: jumpfwd */
    MPX_GAIT_TEST_SPEED       = 15,
    MPX_GAIT_LOOK_UP          = 16,
    MPX_GAIT_LOOK_DOWN        = 17,
    MPX_GAIT_LOOK_LEFT        = 18,
    MPX_GAIT_LOOK_RIGHT       = 19,
    MPX_GAIT_LOOK_UP_LEFT     = 20,   /* firmware name: lookul */
    MPX_GAIT_LOOK_UP_RIGHT    = 21,   /* firmware name: lookur */
    MPX_GAIT_LOOK_DOWN_LEFT   = 22,   /* firmware name: lookll */
    MPX_GAIT_LOOK_DOWN_RIGHT  = 23,   /* firmware name: looklr */
    MPX_GAIT_LIFT_FRONT_LEFT  = 24,   /* firmware name: flegL */
    MPX_GAIT_LIFT_FRONT_RIGHT = 25,   /* firmware name: flegR */
    MPX_GAIT_LIFT_REAR_LEFT   = 26,   /* firmware name: blegL */
    MPX_GAIT_LIFT_REAR_RIGHT  = 27,   /* firmware name: blegR */
    MPX_GAIT_HEIGHT_UP        = 28,
    MPX_GAIT_HEIGHT_DOWN      = 29,
    MPX_GAIT_BALANCE          = 30,
    MPX_GAIT_BOW              = 31,   /* firmware name: bowback */
    MPX_GAIT_BODY_CYCLE       = 32,
    MPX_GAIT_HEAD_ELLIPSE     = 33,
    MPX_GAIT_MOVE_FL          = 34,   /* firmware name: moveLF */
    MPX_GAIT_MOVE_FR          = 35,   /* firmware name: moveRF */
    MPX_GAIT_MOVE_RL          = 36,   /* firmware name: moveLB */
    MPX_GAIT_MOVE_RR          = 37,   /* firmware name: moveRB */
    MPX_GAIT_TROT             = 38,   /* firmware name: stanford */
    MPX_GAIT_FRONT_KICK       = 39,
    MPX_GAIT_WIGGLE           = 40,
    MPX_GAIT_BUTT_SHRUG       = 41,
    MPX_GAIT_WIGGLE_LEFT      = 42,   /* firmware name: wiggleL */
    MPX_GAIT_WIGGLE_RIGHT     = 43,   /* firmware name: wiggleR */
    MPX_GAIT_BUTT_SHRUG_LEFT  = 44,   /* firmware name: buttshrugL */
    MPX_GAIT_BUTT_SHRUG_RIGHT = 45,   /* firmware name: buttshrugR */
} mpx_gait_t;

/** How a gait behaves when it reaches the end of its motion. */
typedef enum {
    MPX_GAIT_HOLDS   = 0,  /**< Stays in its final pose until you change it. */
    MPX_GAIT_RETURNS = 1,  /**< Performs once, returns to standing itself.   */
    MPX_GAIT_CYCLES  = 2,  /**< Repeats until stopped.                       */
} mpx_gait_kind_t;

typedef struct {
    mpx_gait_t       gait;
    const char      *wire_name;   /**< What the firmware is sent.            */
    const char      *description;
    mpx_gait_kind_t  kind;
    int              typical_ms;  /**< One performance; 0 = runs until stopped. */
} mpx_gait_info_t;

static const mpx_gait_info_t MPX_GAITS[] = {
    { MPX_GAIT_NONE            , "none"       , "Stop the gait generator; hold the current pose."                          , MPX_GAIT_HOLDS    ,     0 },
    { MPX_GAIT_STAND           , "init"       , "Return to the neutral standing pose."                                     , MPX_GAIT_HOLDS    ,   800 },
    { MPX_GAIT_STEP            , "step"       , "March on the spot."                                                       , MPX_GAIT_CYCLES   ,  1500 },
    { MPX_GAIT_ROLL            , "roll"       , "Roll the body side to side."                                              , MPX_GAIT_CYCLES   ,  1500 },
    { MPX_GAIT_PITCH           , "pitch"      , "Pitch the body nose-up and nose-down."                                    , MPX_GAIT_CYCLES   ,  1500 },
    { MPX_GAIT_STRETCH         , "stretch"    , "Stretch the legs out, like waking up."                                    , MPX_GAIT_RETURNS  ,  2000 },
    { MPX_GAIT_FORWARD         , "advance"    , "Walk forward."                                                            , MPX_GAIT_CYCLES   ,     0 },
    { MPX_GAIT_BACK            , "back"       , "Walk backward."                                                           , MPX_GAIT_CYCLES   ,     0 },
    { MPX_GAIT_STRAFE_LEFT     , "left"       , "Sidestep left without turning."                                           , MPX_GAIT_CYCLES   ,     0 },
    { MPX_GAIT_STRAFE_RIGHT    , "right"      , "Sidestep right without turning."                                          , MPX_GAIT_CYCLES   ,     0 },
    { MPX_GAIT_TURN_LEFT       , "turnL"      , "Spin left on the spot."                                                   , MPX_GAIT_CYCLES   ,     0 },
    { MPX_GAIT_TURN_RIGHT      , "turnR"      , "Spin right on the spot."                                                  , MPX_GAIT_CYCLES   ,     0 },
    { MPX_GAIT_TWERK           , "twerk"      , "Rear-end shimmy. Crowd-pleaser."                                          , MPX_GAIT_CYCLES   ,  2000 },
    { MPX_GAIT_JUMP            , "jump"       , "Jump straight up."                                                        , MPX_GAIT_RETURNS  ,  2000 },
    { MPX_GAIT_JUMP_FORWARD    , "jumpfwd"    , "Jump forward."                                                            , MPX_GAIT_RETURNS  ,  2000 },
    { MPX_GAIT_TEST_SPEED      , "testspeed"  , "Diagnostic speed sweep. Not a display move."                              , MPX_GAIT_CYCLES   ,  3000 },
    { MPX_GAIT_LOOK_UP         , "lookup"     , "Tilt the body to look up."                                                , MPX_GAIT_HOLDS    ,   800 },
    { MPX_GAIT_LOOK_DOWN       , "lookdown"   , "Tilt the body to look down."                                              , MPX_GAIT_HOLDS    ,   800 },
    { MPX_GAIT_LOOK_LEFT       , "lookleft"   , "Turn the body to look left."                                              , MPX_GAIT_HOLDS    ,   800 },
    { MPX_GAIT_LOOK_RIGHT      , "lookright"  , "Turn the body to look right."                                             , MPX_GAIT_HOLDS    ,   800 },
    { MPX_GAIT_LOOK_UP_LEFT    , "lookul"     , "Look up and to the left."                                                 , MPX_GAIT_HOLDS    ,   800 },
    { MPX_GAIT_LOOK_UP_RIGHT   , "lookur"     , "Look up and to the right."                                                , MPX_GAIT_HOLDS    ,   800 },
    { MPX_GAIT_LOOK_DOWN_LEFT  , "lookll"     , "Look down and to the left."                                               , MPX_GAIT_HOLDS    ,   800 },
    { MPX_GAIT_LOOK_DOWN_RIGHT , "looklr"     , "Look down and to the right."                                              , MPX_GAIT_HOLDS    ,   800 },
    { MPX_GAIT_LIFT_FRONT_LEFT , "flegL"      , "Raise the front-left paw."                                                , MPX_GAIT_HOLDS    ,  1200 },
    { MPX_GAIT_LIFT_FRONT_RIGHT, "flegR"      , "Raise the front-right paw."                                               , MPX_GAIT_HOLDS    ,  1200 },
    { MPX_GAIT_LIFT_REAR_LEFT  , "blegL"      , "Raise the rear-left leg."                                                 , MPX_GAIT_HOLDS    ,  1200 },
    { MPX_GAIT_LIFT_REAR_RIGHT , "blegR"      , "Raise the rear-right leg."                                                , MPX_GAIT_HOLDS    ,  1200 },
    { MPX_GAIT_HEIGHT_UP       , "heightup"   , "Stand taller."                                                            , MPX_GAIT_HOLDS    ,   600 },
    { MPX_GAIT_HEIGHT_DOWN     , "heightdown" , "Crouch lower."                                                            , MPX_GAIT_HOLDS    ,   600 },
    { MPX_GAIT_BALANCE         , "balance"    , "Hold level using the IMU."                                                , MPX_GAIT_CYCLES   ,     0 },
    { MPX_GAIT_BOW             , "bowback"    , "Bow: front down, rear up."                                                , MPX_GAIT_HOLDS    ,  1200 },
    { MPX_GAIT_BODY_CYCLE      , "bodycycle"  , "Circle the body over planted feet."                                       , MPX_GAIT_CYCLES   ,  2500 },
    { MPX_GAIT_HEAD_ELLIPSE    , "headellipse", "Trace an ellipse with the front of the body."                             , MPX_GAIT_CYCLES   ,  2500 },
    { MPX_GAIT_MOVE_FL         , "moveLF"     , "Sweep the front-left leg through an arc."                                 , MPX_GAIT_RETURNS  ,  1500 },
    { MPX_GAIT_MOVE_FR         , "moveRF"     , "Sweep the front-right leg through an arc."                                , MPX_GAIT_RETURNS  ,  1500 },
    { MPX_GAIT_MOVE_RL         , "moveLB"     , "Sweep the rear-left leg through an arc."                                  , MPX_GAIT_RETURNS  ,  1500 },
    { MPX_GAIT_MOVE_RR         , "moveRB"     , "Sweep the rear-right leg through an arc."                                 , MPX_GAIT_RETURNS  ,  1500 },
    { MPX_GAIT_TROT            , "stanford"   , "Stanford trot - the smoothest walk. Speed is set by mpx_walk_speed_set().", MPX_GAIT_CYCLES   ,     0 },
    { MPX_GAIT_FRONT_KICK      , "frontkick"  , "Kick forward with a front leg, then recover."                             , MPX_GAIT_RETURNS  ,  2000 },
    { MPX_GAIT_WIGGLE          , "wiggle"     , "Rear up and wiggle."                                                      , MPX_GAIT_CYCLES   ,  2000 },
    { MPX_GAIT_BUTT_SHRUG      , "buttshrug"  , "Front up, rear shrug."                                                    , MPX_GAIT_CYCLES   ,  2000 },
    { MPX_GAIT_WIGGLE_LEFT     , "wiggleL"    , "Wiggle, leaning left."                                                    , MPX_GAIT_CYCLES   ,  2000 },
    { MPX_GAIT_WIGGLE_RIGHT    , "wiggleR"    , "Wiggle, leaning right."                                                   , MPX_GAIT_CYCLES   ,  2000 },
    { MPX_GAIT_BUTT_SHRUG_LEFT , "buttshrugL" , "Butt shrug, leaning left."                                                , MPX_GAIT_CYCLES   ,  2000 },
    { MPX_GAIT_BUTT_SHRUG_RIGHT, "buttshrugR" , "Butt shrug, leaning right."                                               , MPX_GAIT_CYCLES   ,  2000 },
};

#define MPX_GAIT_COUNT ((int)(sizeof(MPX_GAITS) / sizeof(MPX_GAITS[0])))

/** Look a gait up in the catalogue. Returns 0 if the value is not a gait. */
static inline const mpx_gait_info_t *mpx_gait_info(mpx_gait_t g)
{
    for (int i = 0; i < MPX_GAIT_COUNT; ++i)
        if (MPX_GAITS[i].gait == g) return &MPX_GAITS[i];
    return 0;
}

/** The name the firmware knows a gait by, or "" if there is no such gait.
 *  {@link mpx_gait} uses this, so a gait value that is not in the catalogue
 *  becomes a refused call rather than an undefined move. */
static inline const char *mpx_gait_name(mpx_gait_t g)
{
    const mpx_gait_info_t *info = mpx_gait_info(g);
    return info ? info->wire_name : "";
}

/** How long one performance of a gait naturally takes, in ms.
 *  0 means it runs until you stop it. {@link mpx_gait_play} uses this. */
static inline int mpx_gait_typical_ms(mpx_gait_t g)
{
    const mpx_gait_info_t *info = mpx_gait_info(g);
    return info ? info->typical_ms : 0;
}

/** What a gait does when it finishes: holds, returns, or cycles. */
static inline mpx_gait_kind_t mpx_gait_kind(mpx_gait_t g)
{
    const mpx_gait_info_t *info = mpx_gait_info(g);
    return info ? info->kind : MPX_GAIT_HOLDS;
}

/** One line describing a gait, for logs and menus. */
static inline const char *mpx_gait_description(mpx_gait_t g)
{
    const mpx_gait_info_t *info = mpx_gait_info(g);
    return info ? info->description : "";
}

#ifdef __cplusplus
}
#endif

#endif /* MPX_GAITS_H */
