/* mpx/geometry.h — the robot's real dimensions.
 *
 * Every number here is read out of the firmware's own kinematics headers, so
 * it is the same value the built-in gait generator uses. Nothing is measured,
 * estimated, or copied from a document.
 *
 * You need these the moment you write your own inverse kinematics. Getting one
 * wrong does not produce an obvious failure: the leg still moves, the motion
 * still looks reasonable, and the foot quietly lands somewhere other than
 * where you asked. That is worth being careful about, which is why this file
 * is generated rather than typed.
 *
 * Coordinates, everywhere in the SDK:
 *
 *     x   forward positive, backward negative        (mm)
 *     y   left positive, right negative              (mm)
 *     z   UP positive — so a foot below the hip is negative   (mm)
 *
 * GENERATED by `python tools/gen_geometry.py --write` from
 * mangdang/main/robot/{stanford_kinematics,stanford_gait}.h — do not edit.
 */
#ifndef MPX_GEOMETRY_H
#define MPX_GEOMETRY_H

#define MPX_THIGH_MM       50.0f   /**< mm   Hip pivot to knee pivot.                                   (SK_L1) */
#define MPX_CALF_MM        60.0f   /**< mm   Knee pivot to the foot contact point.                      (SK_L2) */
#define MPX_ABDUCT_MM      26.0f   /**< mm   Hip roll axis out to the leg plane.                        (SK_ABDUCTION_OFFSET) */
#define MPX_HIP_X_MM       59.0f   /**< mm   Body centre to a hip, fore/aft. Front is +.                (SK_LEG_FB) */
#define MPX_HIP_Y_MM       23.5f   /**< mm   Body centre to a hip, left/right. Left is +.               (SK_LEG_LR) */
#define MPX_NEUTRAL_Z_MM   70.0f   /**< mm   Body height the firmware's own kinematics rest at.         (SK_NEUTRAL_HEIGHT_MM) */
#define MPX_WALK_Z_MM      80.0f   /**< mm   Body height the built-in walk was tuned at.                (SG_NATIVE_HEIGHT_MM) */
#define MPX_WALK_LIFT_MM   20.0f   /**< mm   Foot lift the built-in walk was tuned at.                  (SG_NATIVE_CLEARANCE_MM) */
#define MPX_WALK_MAX_MM_S 200.0f   /**< mm/s Fastest the built-in walk was tuned for.                   (SG_NATIVE_VX_MM_S) */
#define MPX_GAIT_DT_S     0.015f   /**< s    One tick of the gait generator.                            (SG_DT) */

/** Furthest a foot can be from its hip. Beyond this the leg is straight and
 *  the IK has no solution — {@link mpx_foot_to} clamps rather than failing. */
#define MPX_REACH_MM      (MPX_THIGH_MM + MPX_CALF_MM)

/** A safe, normal standing foot height. Negative because z is up. */
#define MPX_STAND_Z_MM    (-MPX_NEUTRAL_Z_MM)

/** Widest angle any joint accepts, either side of centre. Enforced by the
 *  firmware; asking for more is clamped, not an error. */
#define MPX_JOINT_LIMIT_DEG  135.0f

/** Hip locations in body coordinates, if you are solving for the whole robot
 *  rather than one leg. The body is symmetric, so these are all the same
 *  magnitude — a common mistake is to assume the rear hips sit further out. */
#define MPX_HIP_X_FRONT   ( MPX_HIP_X_MM)
#define MPX_HIP_X_REAR    (-MPX_HIP_X_MM)
#define MPX_HIP_Y_LEFT    ( MPX_HIP_Y_MM)
#define MPX_HIP_Y_RIGHT   (-MPX_HIP_Y_MM)

#endif /* MPX_GEOMETRY_H */
