/* mpx/params.h — the driver board's tunable parameters.
 *
 * Each of these is a slot on the servo's own controller. `mpx_gain_set()`
 * writes one; `mpx_gain_save()` can burn it into the board's flash, where a
 * reboot will not clear it.
 *
 * THE NUMBERS ARE A WIRE PROTOCOL. Writing the wrong slot does not fail — it
 * sets a different parameter. That is why this file is generated from the
 * firmware's own table rather than typed.
 *
 *   MPX_PARAM_REVERSE_POSITION_SENSOR  Flip which way the position sensor counts.
 *                                      Calibration. Changing it re-defines every angle.
 *   MPX_PARAM_MIN_POSITION_ADC         Bottom of the sensor's usable range.
 *                                      Calibration.
 *   MPX_PARAM_MAX_POSITION_ADC         Top of the sensor's usable range.
 *                                      Calibration.
 *   MPX_PARAM_RANGE_POSITION_DEG       Degrees the raw range spans.
 *                                      Calibration.
 *   MPX_PARAM_REVERSE_MOTOR            Flip which way the motor drives.
 *                                      DANGEROUS. One joint moving opposite to the other eleven is how a robot destroys itself.
 *   MPX_PARAM_KP_POSITION              Stiffness: how hard it pulls to target. Stock 65.
 *   MPX_PARAM_KD_POSITION              Damping: resists overshoot. Stock 800.
 *   MPX_PARAM_KP_CURRENT               Gain of the inner current loop.
 *                                      Torque response. Raise it and the joint feels sharper; too far and it buzzes.
 *   MPX_PARAM_KFF_CURRENT              Current fed forward from the position error.
 *                                      Anticipation. Helps a joint under constant load (the robot's own weight) stop sagging.
 *   MPX_PARAM_MAX_PWM_DUTY_CYCLE       Ceiling on drive effort, 0..1.
 *                                      Your torque limit. Lower it to make a joint physically unable to hurt anything.
 *
 * READ-ONLY FROM A SKILL: the calibration parameters decide what every angle
 * MEANS. Change one and every command afterwards means something different,
 * including the built-in gaits'. They return MPX_ERR_READONLY here; change
 * them from Servo Studio, with a human watching the joint move.
 *
 * GENERATED by `python tools/gen_params.py --write` from
 * mangdang/main/robot/driver_board.{h,c} and the firmware's read-only list.
 */
#ifndef MPX_PARAMS_H
#define MPX_PARAMS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    MPX_PARAM_REVERSE_POSITION_SENSOR  = 0,  /* read-only from a skill */
    MPX_PARAM_MIN_POSITION_ADC         = 1,  /* read-only from a skill */
    MPX_PARAM_MAX_POSITION_ADC         = 2,  /* read-only from a skill */
    MPX_PARAM_RANGE_POSITION_DEG       = 3,  /* read-only from a skill */
    MPX_PARAM_REVERSE_MOTOR            = 4,  /* read-only from a skill */
    MPX_PARAM_KP_POSITION              = 5,
    MPX_PARAM_KD_POSITION              = 6,
    MPX_PARAM_KP_CURRENT               = 7,
    MPX_PARAM_KFF_CURRENT              = 8,
    MPX_PARAM_MAX_PWM_DUTY_CYCLE       = 9,
} mpx_param_t;

typedef struct {
    mpx_param_t  param;
    const char  *name;      /**< What the firmware and Servo Studio call it. */
    int          read_only; /**< 1 = refused from a skill.                   */
} mpx_param_info_t;

static const mpx_param_info_t MPX_PARAMS[] = {
    { MPX_PARAM_REVERSE_POSITION_SENSOR , "reverse_position_sensor", 1 },
    { MPX_PARAM_MIN_POSITION_ADC        , "min_position_adc", 1 },
    { MPX_PARAM_MAX_POSITION_ADC        , "max_position_adc", 1 },
    { MPX_PARAM_RANGE_POSITION_DEG      , "range_position_deg", 1 },
    { MPX_PARAM_REVERSE_MOTOR           , "reverse_motor", 1 },
    { MPX_PARAM_KP_POSITION             , "kp_position", 0 },
    { MPX_PARAM_KD_POSITION             , "kd_position", 0 },
    { MPX_PARAM_KP_CURRENT              , "kp_current", 0 },
    { MPX_PARAM_KFF_CURRENT             , "kff_current", 0 },
    { MPX_PARAM_MAX_PWM_DUTY_CYCLE      , "max_pwm_duty_cycle", 0 },
};

#define MPX_PARAM_COUNT ((int)(sizeof(MPX_PARAMS) / sizeof(MPX_PARAMS[0])))

/** The firmware's name for a parameter, or "". */
static inline const char *mpx_param_name(mpx_param_t p)
{
    for (int i = 0; i < MPX_PARAM_COUNT; ++i)
        if (MPX_PARAMS[i].param == p) return MPX_PARAMS[i].name;
    return "";
}

/** 1 if a skill may not write this one. Checking beats discovering. */
static inline int mpx_param_read_only(mpx_param_t p)
{
    for (int i = 0; i < MPX_PARAM_COUNT; ++i)
        if (MPX_PARAMS[i].param == p) return MPX_PARAMS[i].read_only;
    return 0;
}

#ifdef __cplusplus
}
#endif

#endif /* MPX_PARAMS_H */
