#!/usr/bin/env python3
"""Generate sdk/include/mpx/geometry.h from the firmware's kinematics headers.

Link lengths are the constants a maker is most likely to get wrong and least
likely to notice: a leg IK built on a calf that is 4 mm too short still moves,
still looks plausible, and lands the foot in the wrong place.

This repo shipped exactly that bug. `mpx/leg.h` carried `MPX_CALF_MM 56.0f`,
copied from an older document, while the firmware's own
`robot/stanford_kinematics.h` says:

    #define SK_L2  60.0f   /* LEG_L2 = 0.060 m (exact, not 56) */

The comment "exact, not 56" is the firmware author already having been caught
by this once. Hand-copying was the mistake; this script is the fix.

    python tools/gen_geometry.py --check     verify (CI)
    python tools/gen_geometry.py --write     regenerate
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FW = ROOT.parent / "mangdang" / "main" / "robot"
OUT = ROOT / "sdk" / "include" / "mpx" / "geometry.h"

# (firmware #define, SDK name, unit, what it is)
WANTED = [
    ("SK_L1",                "MPX_THIGH_MM",      "mm",   "Hip pivot to knee pivot."),
    ("SK_L2",                "MPX_CALF_MM",       "mm",   "Knee pivot to the foot contact point."),
    ("SK_ABDUCTION_OFFSET",  "MPX_ABDUCT_MM",     "mm",   "Hip roll axis out to the leg plane."),
    ("SK_LEG_FB",            "MPX_HIP_X_MM",      "mm",   "Body centre to a hip, fore/aft. Front is +."),
    ("SK_LEG_LR",            "MPX_HIP_Y_MM",      "mm",   "Body centre to a hip, left/right. Left is +."),
    ("SK_NEUTRAL_HEIGHT_MM", "MPX_NEUTRAL_Z_MM",  "mm",   "Body height the firmware's own kinematics rest at."),
    ("SG_NATIVE_HEIGHT_MM",  "MPX_WALK_Z_MM",     "mm",   "Body height the built-in walk was tuned at."),
    ("SG_NATIVE_CLEARANCE_MM","MPX_WALK_LIFT_MM", "mm",   "Foot lift the built-in walk was tuned at."),
    ("SG_NATIVE_VX_MM_S",    "MPX_WALK_MAX_MM_S", "mm/s", "Fastest the built-in walk was tuned for."),
    ("SG_DT",                "MPX_GAIT_DT_S",     "s",    "One tick of the gait generator."),
]
SOURCES = ["stanford_kinematics.h", "stanford_gait.h"]


def parse() -> dict[str, str]:
    found: dict[str, str] = {}
    for name in SOURCES:
        path = FW / name
        if not path.is_file():
            sys.exit(f"error: {path} not found.\n"
                     f"       This generator reads the firmware repo. Expected it at "
                     f"{FW.parent.parent}")
        text = path.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r"^#define\s+(SK_\w+|SG_\w+)\s+([-+0-9.eEf]+)", text, re.M):
            found.setdefault(m.group(1), m.group(2))
    return found


def render(vals: dict[str, str]) -> str:
    rows = []
    for fw_name, sdk_name, unit, what in WANTED:
        if fw_name not in vals:
            sys.exit(f"error: {fw_name} not found in the firmware kinematics headers.")
        v = vals[fw_name]
        if not v.endswith("f") and "." in v:
            v += "f"
        rows.append((sdk_name, v, unit, what, fw_name))

    width = max(len(r[0]) for r in rows)
    vwidth = max(len(r[1]) for r in rows)
    body = "\n".join(
        f"#define {n:<{width}} {v:>{vwidth}}   /**< {u:<4} {w:<58} ({fw}) */"
        for n, v, u, w, fw in rows)

    return f'''/* mpx/geometry.h — the robot's real dimensions.
 *
 * Every number here is read out of the firmware's own kinematics headers, so
 * it is the same value the built-in gait generator uses. Nothing is measured,
 * estimated, or copied from a document.
 *
 * You need these the moment you write your own inverse kinematics. Getting one
 * wrong does not produce an obvious failure: the leg still moves, the motion
 * still looks reasonable, and the foot quietly lands somewhere other than
 * where you asked. That is worth being careful about, which is why this file
 * is generated rather than typed.
 *
 * Coordinates, everywhere in the SDK:
 *
 *     x   forward positive, backward negative        (mm)
 *     y   left positive, right negative              (mm)
 *     z   UP positive — so a foot below the hip is negative   (mm)
 *
 * GENERATED by `python tools/gen_geometry.py --write` from
 * mangdang/main/robot/{{stanford_kinematics,stanford_gait}}.h — do not edit.
 */
#ifndef MPX_GEOMETRY_H
#define MPX_GEOMETRY_H

{body}

/** Furthest a foot can be from its hip. Beyond this the leg is straight and
 *  the IK has no solution — {{@link mpx_foot_to}} clamps rather than failing. */
#define MPX_REACH_MM      (MPX_THIGH_MM + MPX_CALF_MM)

/** A safe, normal standing foot height. Negative because z is up. */
#define MPX_STAND_Z_MM    (-MPX_NEUTRAL_Z_MM)

/** Widest angle any joint accepts, either side of centre. Enforced by the
 *  firmware; asking for more is clamped, not an error. */
#define MPX_JOINT_LIMIT_DEG  135.0f

/** Hip locations in body coordinates, if you are solving for the whole robot
 *  rather than one leg. The body is symmetric, so these are all the same
 *  magnitude — a common mistake is to assume the rear hips sit further out. */
#define MPX_HIP_X_FRONT   ( MPX_HIP_X_MM)
#define MPX_HIP_X_REAR    (-MPX_HIP_X_MM)
#define MPX_HIP_Y_LEFT    ( MPX_HIP_Y_MM)
#define MPX_HIP_Y_RIGHT   (-MPX_HIP_Y_MM)

#endif /* MPX_GEOMETRY_H */
'''


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    text = render(parse())
    have = OUT.read_text(encoding="utf-8") if OUT.is_file() else None

    if args.check:
        if have != text:
            print(f"STALE  {OUT.relative_to(ROOT)}")
            print("       run: python tools/gen_geometry.py --write")
            return 1
        print(f"  ok    {OUT.relative_to(ROOT)}")
        return 0

    if args.write:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text, encoding="utf-8")
        print(("  unchanged " if have == text else "  updated   ") + str(OUT.relative_to(ROOT)))
        return 0

    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
