#!/usr/bin/env python3
"""Single source of truth for the host ABI.

The firmware's NativeSymbol table is the only place a host function really
exists. Everything else that describes it -- the JSON, the C header, the
AssemblyScript bindings, the WAT reference -- is generated from that table by this script, so none of them can drift away from it.

    python tools/gen_abi.py --check     verify everything is in sync (CI)
    python tools/gen_abi.py --write     regenerate everything

`--check` exits non-zero on any drift, and prints exactly what moved.

Why this matters: before it existed, four hand-maintained copies of the same
header lived in this repo and two of them had gone stale -- one still described
ABI v1 and would trap on its first host call. That is not a discipline problem,
it is a design problem, and this script is the fix.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_FIRMWARE = ROOT.parent / "mangdang" / "main" / "sdk" / "wasm_host_functions.h"

# WAMR signature letters -> what they mean on each side of the boundary.
TYPES = {
    "i": ("int",   "i32",   "int32"),
    "I": ("long long", "i64", "int64"),
    "f": ("float", "f32",   "f32"),
    "F": ("double","f64",   "f64"),
    "$": ("const char *", "i32", "usize"),   # string; WAMR converts the pointer
    "*": ("void *", "i32",  "usize"),
}

ERRORS = [
    ("MPX_OK",              0, "Success."),
    ("MPX_ERR_ARG",        -1, "Bad argument: id, index or pointer."),
    ("MPX_ERR_NOT_LOCKED", -2, "You do not hold the servo bus."),
    ("MPX_ERR_NO_REPLY",   -3, "The driver board did not answer."),
    ("MPX_ERR_READONLY",   -4, "Calibration parameter; read-only."),
    ("MPX_ERR_CANCELLED",  -5, "Your skill was stopped mid-call."),
    ("MPX_ERR_STATE",      -6, "Right call, wrong time."),
    ("MPX_ERR_BUSY",       -7, "Another control domain holds the joints."),
]


def parse_firmware(path: pathlib.Path):
    """Pull the ABI version and the NativeSymbol table out of the firmware."""
    text = path.read_text(encoding="utf-8", errors="replace")

    m = re.search(r"MPX_ABI_VERSION\s*=\s*(\d+)", text)
    if not m:
        sys.exit(f"error: no MPX_ABI_VERSION in {path}")
    version = int(m.group(1))

    start = text.find("NATIVE_SYMBOLS[] = {")
    if start < 0:
        sys.exit(f"error: no NATIVE_SYMBOLS table in {path}")
    block = text[start : text.index("\n};", start)]

    symbols = []
    for name, sig in re.findall(r'\{\s*"([a-zA-Z_0-9]+)"\s*,[^,]+,\s*"([^"]*)"', block):
        args, _, ret = sig.partition(")")
        symbols.append({
            "name": name,
            "signature": sig,
            "args": list(args.lstrip("(")),
            "returns": ret or None,
        })

    dupes = {s["name"] for s in symbols if [x["name"] for x in symbols].count(s["name"]) > 1}
    if dupes:
        sys.exit(f"error: duplicate symbols in the firmware table: {sorted(dupes)}")

    return version, symbols


def c_decl(sym) -> str:
    ret = TYPES[sym["returns"]][0] if sym["returns"] else "void"
    if not sym["args"]:
        args = "void"
    else:
        args = ", ".join(f"{TYPES[a][0]} a{i}" for i, a in enumerate(sym["args"]))
    return f"extern {ret} {sym['name']}({args});"


def ts_decl(sym) -> str:
    ret = {"i": "i32", "f": "f32", "I": "i64", "F": "f64"}.get(sym["returns"] or "", "void")
    if sym["returns"] is None:
        ret = "void"
    args = ", ".join(
        f"a{i}: " + {"i": "i32", "f": "f32", "$": "usize", "*": "usize",
                     "I": "i64", "F": "f64"}[a]
        for i, a in enumerate(sym["args"])
    )
    return f"export declare function {sym['name']}({args}): {ret};"


def wat_decl(sym) -> str:
    params = " ".join(f"({TYPES[a][1]})".replace("(", "param ").replace(")", "")
                      for a in sym["args"])
    params = " ".join(f"(param {TYPES[a][1]})" for a in sym["args"])
    result = f" (result {TYPES[sym['returns']][1]})" if sym["returns"] else ""
    return f'(import "env" "{sym["name"]}" (func ${sym["name"]}{" " + params if params else ""}{result}))'


def render_json(version, symbols) -> str:
    return json.dumps({
        "abi_version": version,
        "symbol_count": len(symbols),
        "_note": ("GENERATED by tools/gen_abi.py from the firmware's NativeSymbol "
                  "table. Do not edit: change the firmware and regenerate."),
        "error_codes": [{"name": n, "code": c, "meaning": m} for n, c, m in ERRORS],
        "types": {k: {"c": v[0], "wasm": v[1]} for k, v in TYPES.items()},
        "symbols": symbols,
    }, indent=2) + "\n"


def render_ts(version, symbols) -> str:
    lines = [
        "// mpx_env.ts — the raw host imports for AssemblyScript skills.",
        "//",
        "// GENERATED by tools/gen_abi.py. Do not edit.",
        f"// ABI version {version}, {len(symbols)} symbols.",
        "",
        f"export const MPX_ABI_VERSION: i32 = {version};",
        "",
    ]
    lines += [f"export const {n}: i32 = {c};" for n, c, _ in ERRORS]
    lines += ["", '@external("env", "__placeholder__")', ""]
    lines = lines[:-3] + [""]
    for s in symbols:
        lines.append(f'@external("env", "{s["name"]}")')
        lines.append(ts_decl(s))
        lines.append("")
    return "\n".join(lines)


def render_wat(version, symbols) -> str:
    out = [f"# WAT host imports — ABI v{version}, {len(symbols)} symbols",
           "",
           "GENERATED by `tools/gen_abi.py`. Do not edit.",
           "",
           "Paste the imports you need at the top of your module.",
           "",
           "```wat"]
    out += [wat_decl(s) for s in symbols]
    out += ["```", ""]
    return "\n".join(out)


def render_reference(version, symbols) -> str:
    out = [
        "# Host function reference",
        "",
        f"ABI version **{version}** — **{len(symbols)}** functions.",
        "",
        "GENERATED by `tools/gen_abi.py` from the firmware's own symbol table.",
        "Do not edit this file; it is regenerated and CI fails on drift.",
        "",
        "These are the raw imports. Most of the time you want the friendly",
        "wrappers in `sdk/include/mpx/` instead — see",
        "[the guide](../MOVEMENT.md). Every wrapper is a",
        "`static inline` over exactly one of these, so nothing here is hidden",
        "from you and nothing costs extra.",
        "",
        "## Error codes",
        "",
        "| Code | Name | Meaning |",
        "|---:|---|---|",
    ]
    out += [f"| `{c}` | `{n}` | {m} |" for n, c, m in ERRORS]
    out += ["", "## Functions", "",
            "| Function | C signature | Wire signature |", "|---|---|---|"]
    for s in symbols:
        out.append(f"| `{s['name']}` | `{c_decl(s)[7:-1]}` | `{s['signature']}` |")
    out.append("")
    return "\n".join(out)


def render_errors_doc(version) -> str:
    out = ["# Error codes", "",
           f"ABI v{version}. GENERATED by `tools/gen_abi.py`; do not edit.", "",
           "Every host function returns one of these. `0` is success; anything",
           "negative is a failure. Functions documented to return data return a",
           "non-negative value instead.", "",
           "`mpx_strerror(code)` turns any of them into text.", "",
           "| Code | Name | Meaning |", "|---:|---|---|"]
    out += [f"| `{c}` | `{n}` | {m} |" for n, c, m in ERRORS]
    out.append("")
    return "\n".join(out)


TARGETS = {
    "abi/host_functions.json":        render_json,
    "sdk/assemblyscript/mpx_env.ts":  render_ts,
    "sdk/wat/host-functions.md":      render_wat,
}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--firmware", type=pathlib.Path, default=DEFAULT_FIRMWARE,
                    help="path to main/sdk/wasm_host_functions.h in the firmware repo")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true", help="fail if anything is out of date")
    g.add_argument("--write", action="store_true", help="regenerate everything")
    args = ap.parse_args()

    if not args.firmware.exists():
        print(f"error: firmware header not found at {args.firmware}", file=sys.stderr)
        print("       pass --firmware <path> if your checkout is laid out differently",
              file=sys.stderr)
        return 2

    version, symbols = parse_firmware(args.firmware)

    rendered = {p: fn(version, symbols) for p, fn in TARGETS.items()}

    # The C header is hand-written prose around a generated body, so it is
    # checked rather than overwritten: its declarations must match, its comments
    # are ours to write.
    header = (ROOT / "sdk/include/mpx/abi.h").read_text(encoding="utf-8")
    missing = [s["name"] for s in symbols
               if not re.search(rf"\b{re.escape(s['name'])}\s*\(", header)]
    extra_v = re.search(r"#define MPX_ABI_VERSION (\d+)", header)

    problems = []
    if missing:
        problems.append(f"sdk/include/mpx/abi.h is missing: {', '.join(missing)}")
    if not extra_v or int(extra_v.group(1)) != version:
        problems.append(f"sdk/include/mpx/abi.h declares ABI "
                        f"{extra_v.group(1) if extra_v else '?'}, firmware says {version}")

    for rel, text in rendered.items():
        path = ROOT / rel
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            if current != text:
                path.write_text(text, encoding="utf-8")
                print(f"  updated {rel}")
        elif current != text:
            problems.append(f"{rel} is out of date")

    if args.write:
        print(f"ABI v{version}, {len(symbols)} symbols — generated from {args.firmware}")
        if problems:
            for p in problems:
                print(f"  ! {p}")
            return 1
        return 0

    if problems:
        print("ABI drift detected:")
        for p in problems:
            print(f"  ! {p}")
        print("\nRun: python tools/gen_abi.py --write")
        return 1

    print(f"ABI v{version}, {len(symbols)} symbols — everything in sync")
    return 0


if __name__ == "__main__":
    sys.exit(main())
