#!/usr/bin/env python3
"""Generate the reference pages that must never be written by hand.

    python tools/gen_docs.py --write
    python tools/gen_docs.py --check      # CI

Anything a human types twice eventually says two different things. The gait
catalogue and the CLI reference both already exist in machine-readable form --
one in the generated header, one in argparse -- so this script projects them
into docs/ rather than asking anyone to keep a third copy in step.

Host functions and error codes are generated by tools/gen_abi.py, which owns
the firmware side of the same idea.
"""
from __future__ import annotations

import argparse
import io
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

_ROW = re.compile(
    r'\{\s*(MPX_GAIT_[A-Z_0-9]+)\s*,\s*"([^"]+)"\s*,\s*'
    r'((?:"(?:[^"\\]|\\.)*"\s*)+),\s*(MPX_GAIT_[A-Z]+)\s*,\s*(-?\d+)\s*\}')

_ENDING = {"MPX_GAIT_HOLDS": "holds", "MPX_GAIT_RETURNS": "returns",
           "MPX_GAIT_CYCLES": "cycles"}


def gaits_page() -> str:
    text = (ROOT / "sdk/include/mpx/gaits.h").read_text(encoding="utf-8")
    rows = []
    for enum, wire, summary_raw, ending, ms in _ROW.findall(text):
        summary = "".join(re.findall(r'"((?:[^"\\]|\\.)*)"', summary_raw)).strip()
        rows.append((enum, wire, summary, _ENDING.get(ending, ending), int(ms)))

    out = io.StringIO()
    w = out.write
    w("# Gait catalogue\n\n")
    w(f"The **{len(rows)}** movements the firmware already knows how to perform.\n\n")
    w("GENERATED by `tools/gen_docs.py` from `sdk/include/mpx/gaits.h`, which is\n"
      "itself generated from the firmware's `robot::GaitCmd` enum. Do not edit.\n\n")
    w("```c\n"
      "mpx_gait(MPX_GAIT_FORWARD);            // start it, return immediately\n"
      "mpx_gait_for(MPX_GAIT_TWERK, 2000);    // start, hold 2 s, stop\n"
      "mpx_gait_once(MPX_GAIT_STRETCH);       // start, hold for TYPICAL, stop\n"
      "mpx_gait_stop();                       // stop; the pose is held\n"
      "```\n\n")
    w("Same list on the terminal, searchable: `mpx-cli gaits [text]`\n\n")
    w("## What ENDING means\n\n"
      "This is the column people trip over.\n\n"
      "| Ending | What happens when you stop asking |\n|---|---|\n"
      "| `holds` | Stays in its final pose. **It will still be there when your skill exits.** |\n"
      "| `returns` | Comes back to standing on its own. |\n"
      "| `cycles` | Repeats until you stop it. |\n\n"
      "`TYPICAL` is a duration that suits the movement; `-` means it runs until\n"
      "stopped. `mpx_gait_once()` uses it so you do not have to guess.\n\n")
    w("## The catalogue\n\n| Name | Wire name | Ending | Typical | What it does |\n"
      "|---|---|---|---:|---|\n")
    for enum, wire, summary, ending, ms in rows:
        w(f"| `{enum}` | `{wire}` | {ending} | {str(ms)+' ms' if ms else '—'} | {summary} |\n")
    w("\n> **Wire name** is what the firmware matches on. You should never need it —\n"
      "> `mpx_gait()` takes the enum, so a typo is a compile error instead of a\n"
      "> robot that quietly does nothing.\n")
    return out.getvalue()


def cli_page(embedded: bool = False) -> str:
    """The CLI reference.

    `embedded=True` drops the page title, the GENERATED note and the
    "## Commands" heading, because reference_page() supplies its own. It
    used to splice this page in by line index, which emitted the heading
    twice and put a "do not edit" note in the middle of another document.
    """
    sys.path.insert(0, str(ROOT / "cli" / "src"))
    try:
        from mpx_cli.cli import build_parser
    except Exception as exc:                      # pragma: no cover
        return f"# CLI reference\n\nCould not import mpx_cli: {exc}\n"

    parser = build_parser()
    out = io.StringIO()
    w = out.write
    if not embedded:
        w("# CLI reference\n\n")
        w("GENERATED by `tools/gen_docs.py` from the CLI's own argument parser.\n"
          "Do not edit; it cannot then disagree with `--help`.\n\n")
    w(("### " if embedded else "## ") + "The loop you will actually run\n\n```bash\n"
      "mpx-cli init my_move      # scaffold a skill\n"
      "cd my_move\n"
      "mpx-cli deploy            # build + upload + run, in one\n"
      "mpx-cli logs -f           # what the robot is saying\n"
      "```\n\n")
    w("Run from inside a skill directory and every path is derived from\n"
      "`manifest.json`, so you never retype the name.\n\n")

    subs = [a for a in parser._actions
            if isinstance(a, argparse._SubParsersAction)]
    # argparse exposes an alias as its own choice pointing at the SAME parser
    # object, so `ls` was emitted as a command in its own right with an empty
    # description. Group by parser identity and name the alias on the row it
    # belongs to.
    canonical: list[str] = []
    alias_of: dict[str, list[str]] = {}
    first_seen: dict[int, str] = {}
    if subs:
        for name, sub in subs[0].choices.items():
            key = id(sub)
            if key in first_seen:
                alias_of.setdefault(first_seen[key], []).append(name)
            else:
                first_seen[key] = name
                canonical.append(name)

    def _label(name: str) -> str:
        extra = alias_of.get(name)
        return f"`mpx-cli {name}`" + (f" (or `{extra[0]}`)" if extra else "")

    if not embedded:
        w("## Commands\n\n")
    w("| Command | What it does |\n|---|---|\n")
    if subs:
        for name in canonical:
            sub = subs[0].choices[name]
            desc = (sub.description or "").strip() or _help_of(subs[0], name)
            w(f"| [{_label(name)}](#mpx-cli-{name}) | {desc} |\n")
    w("\n")

    if subs:
        for name in canonical:
            sub = subs[0].choices[name]
            w(f"### `mpx-cli {name}`\n\n")
            if name in alias_of:
                w("Alias: " + ", ".join(f"`mpx-cli {a}`" for a in alias_of[name]) + "\n\n")
            desc = (sub.description or "").strip()
            if desc:
                w(desc + "\n\n")
            rows = []
            for act in sub._actions:
                if act.dest == "help":
                    continue
                flags = ", ".join(f"`{o}`" for o in act.option_strings) or f"`{act.dest}`"
                helptext = (act.help or "").replace("\n", " ").strip()
                rows.append((flags, helptext))
            if rows:
                w("| Option | Meaning |\n|---|---|\n")
                for flags, helptext in rows:
                    w(f"| {flags} | {helptext} |\n")
                w("\n")

    w("## Settings\n\n| Variable | Default | Meaning |\n|---|---|---|\n"
      "| `MPX_HOST` | `192.168.2.1` | Robot address |\n"
      "| `MPX_PORT` | `80` | Robot port |\n"
      "| `MPX_SDK_INCLUDE` | auto | Where the SDK headers are, if not found automatically |\n\n"
      "Put the first two in a `.env` beside your project and stop typing `--ip`.\n")
    return out.getvalue()


def _help_of(subaction, name: str) -> str:
    for choice in subaction._choices_actions:
        if choice.dest == name:
            return (choice.help or "").strip()
    return ""


def reference_page() -> str:
    """docs/REFERENCE.md — one lookup page, assembled from the generated parts.

    Four separate reference files meant a maker had to know which one held the
    thing they wanted. The content still comes from the firmware and from
    argparse; only the packaging changed.
    """
    import json
    root = pathlib.Path(__file__).resolve().parent.parent
    abi = json.loads((root / "abi" / "host_functions.json").read_text(encoding="utf-8"))

    errors = "\n".join(
        f"| `{e['name']}` | `{e['code']}` | {e['meaning']} |"
        for e in abi.get("error_codes", []))

    # Grouped by prefix, which is how the SDK headers are split, so the table
    # reads in the same order someone met the functions in.
    order = [("mpx_abi", "ABI"), ("print", "Logging"), ("robot_gait", "Gaits"),
             ("robot_set_body", "Body"), ("robot_set_config", "Gait config"),
             ("robot_ik", "Feet"), ("robot_", "Joints and sensing"),
             ("servo_", "Servo bus"), ("mpx_", "v3/v4 additions")]
    seen, hosts = set(), []
    for prefix, title in order:
        rows = [s2 for s2 in abi["symbols"]
                if s2["name"] not in seen and s2["name"].startswith(prefix)]
        if not rows:
            continue
        hosts.append(f"\n**{title}**\n")
        hosts.append("| Function | Signature |\n|---|---|")
        for s2 in rows:
            seen.add(s2["name"])
            hosts.append(f"| `{s2['name']}` | `{s2['signature']}` |")
    host_md = "\n".join(hosts)

    return f"""# Reference

Everything you look up rather than read. **Generated** from the firmware's own
tables and from the CLI itself, so it cannot drift from what the robot does.

* [When something goes wrong](#when-something-goes-wrong)
* [Error codes](#error-codes)
* [The manifest](#the-manifest)
* [Commands](#commands)
* [Built-in movements](#built-in-movements)
* [Host functions](#host-functions)

---

## When something goes wrong

```bash
mpx-cli doctor      # is the setup right?
mpx-cli logs -f     # what is the robot actually saying?
```

| Symptom | Almost always means |
|---|---|
| `no on_start export` | your entry point is not named `on_start`, or was not exported — use `MPX_EXPORT` |
| `load failed — not a valid .wasm` | the file is corrupt, or is not a module |
| `trapped during execution` | out-of-bounds access, or a divide by zero |
| `timed out (60 s)` | your loop does not finish — or you meant `"behaviour": true` |
| traps on the first host call | built against a different ABI. `mpx-cli doctor`, then rebuild |
| runs, but nothing moves | you forgot `mpx_frame_send()` |
| joints move the wrong way | you closed a loop on `mpx_joint_raw()` — use `mpx_joint_at()` |
| `a skill is already running` | one at a time. `mpx-cli stop` |
| the robot froze in a pose | a `holds` movement, doing what it says. Send `init` |
| a control loop diverges | same frame mistake as above, or a gain that is too high |
| autorun stopped happening | safe mode tripped. `mpx-cli safe-mode` |
| `MPX_ERR_READONLY` | that parameter is board calibration, not a gain |
| `MPX_ERR_BUSY` | another domain holds the joints — see `mpx_take()` |

If the SDK behaves differently from the documentation, treat the documentation
as the thing that is wrong, and please report it.

---

## Error codes

Every host function returns one of these, or a value `>= 0` where it is
documented to return data. `mpx_strerror(code)` turns any of them into text.

| Name | Value | Meaning |
|---|---|---|
{errors}

---

## The manifest

`manifest.json` is the one file the CLI and the robot both read. `mpx-cli build`
embeds the declarative fields into the `.wasm` itself, so they travel with the
artifact.

| Field | Type | What it does |
|---|---|---|
| `slug` | string | the identifier; the source file and the robot filename derive from it |
| `title` | string | shown in the marketplace |
| `version` | string | semver |
| `abi` | int | the ABI this was built for. `mpx-cli` refuses a mismatch before upload |
| `readme` | string | one-line description |
| `params` | array | tunable at run time; the web UI renders a control per entry |
| `provides_gait` | string | registers a movement name the phone can trigger |
| `behaviour` | bool | no 60-second watchdog; must be stopped |
| `on` | array | events that start it: `boot`, `imu.lifted`, `imu.fallen`, `imu.shaken`, `chat:<word>` |
| `autorun` | bool | start at power-on, subject to safe mode |

A parameter entry is `{{"name","type","default"}}` plus optional `min`, `max`
and `label`. `type` is `float` or `int`.

---

## Commands

{cli_page(embedded=True)}

---

## Built-in movements

{gaits_page().split(chr(10), 2)[2] if True else ""}

---

## Host functions

The raw imports, as the firmware registers them. The friendly wrappers in
`mpx/*.h` compile down to these with nothing added — read this to know what a
call really costs.

**ABI v{abi['abi_version']} · {abi['symbol_count']} functions**
{host_md}
"""


TARGETS = {"docs/REFERENCE.md": reference_page}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true")
    g.add_argument("--write", action="store_true")
    args = ap.parse_args()

    stale = []
    for rel, fn in TARGETS.items():
        path = ROOT / rel
        text = fn()
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            if current != text:
                path.write_text(text, encoding="utf-8")
                print(f"  updated {rel}")
        elif current != text:
            stale.append(rel)

    if stale:
        print("Generated docs are out of date:")
        for s in stale:
            print(f"  ! {s}")
        print("\nRun: python tools/gen_docs.py --write")
        return 1
    if args.check:
        print("generated docs in sync")
    return 0


if __name__ == "__main__":
    sys.exit(main())
